<?php

namespace AdminBundle\Repository;

/**
 * DahTrainingMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DahTrainingMaterialRepository extends \Doctrine\ORM\EntityRepository
{
}
