<?php
/*

- Use PAYTM_ENVIRONMENT as 'PROD' if you wanted to do transaction in production environment else 'TEST' for doing transaction in testing environment.
- Change the value of PAYTM_MERCHANT_KEY constant with details received from Paytm.
- Change the value of PAYTM_MERCHANT_MID constant with details received from Paytm.
- Change the value of PAYTM_MERCHANT_WEBSITE constant with details received from Paytm.
- Above details will be different for testing and production environment.

*/


$paytmErrCodes = array(
				"01"=>"Txn Successfull.",
				"04"=>"Closed",
				"05"=>"Open",
				"06"=>"Pending",
				"10"=>"Refund Successful.",
				"11"=>"Refund because another transaction with same order id retrieved by the user.",
				"100"=>"Paytm has classified the transaction as suspicious",
				"105"=>"The user has made 3 unsuccessful attempts. The transaction has been classified as suspicious and user has been blocked.",
				"106"=>"Max Txn amount is crossed for Cust Id",
				"107"=>"Perday Txn amount is crossed for Cust Id",
				"108"=>"PerWeek Txn amount is crossed for Cust Id",
				"109"=>"PerMonth Txn amount is crossed for Cust Id",
				"120"=>"Perday Txn count is crossed for Cust Id",
				"121"=>"PerWeek Txn count is crossed for Cust Id",
				"122"=>"PerMonth Txn count is crossed for Cust Id",
				"118"=>"The transaction amount specified by the user exceeds the per transaction limit for this merchant.",
				"119"=>"Perday Txn amount is crossed",
				"130"=>"USER is blocked at Paytm end.",
				"132"=>"IP Address is blocked at Paytm end.",
				"133"=>"Mobile No. is blocked at Paytm end.",
				"134"=>"Subscriber is blocked with the given DL Number,PAN Card,Email Id and MSISDN",
				"140"=>"Invalid Input Parameter from Merchant",
				"141"=>"Cancel Request by Customer",
				"142"=>"Cancel Request by Customer at login screen",
				"150"=>"Duplicate Transaction as similar transaction was seen in 30 sec",
				"151"=>"Transaction with the same order Id already exists",
				"152"=>"Merchant is not associated with channel",
				"153"=>"Channel is not configured with the Payment Mode,Auth Mode and Communication Mode.",
				"155"=>"Per Txn amount is crossed for wallet",
				"156"=>"Perday Txn amount is crossed for wallet",
				"157"=>"PerWeek Txn amount is crossed for wallet",
				"158"=>"PerMonth Txn amount is crossed for wallet",
				"159"=>"Perday Txn count is crossed for wallet",
				"160"=>"PerWeek Txn count is crossed for wallet",
				"161"=>"PerMonth Txn count is crossed for wallet",
				"162"=>"Maximum wrong attempts limit allowed crossed for wallet",
				"163"=>"Could not pass velocity check for wallet",
				"164"=>"Wallet through put limit failure.",
				"226"=>"some error at response parsing",
				"227"=>"Txn Failed",
				"233"=>"Authorization Failed.",
				"234"=>"Invalid Username/Password.",
				"235"=>"Insufficent balance.",
				"236"=>"Wallet does not exist.",
				"237"=>"Could not complete request. Please retry again.",
				"238"=>"Invalid currency code.",
				"239"=>"Merchant does not exist.",
				"243"=>"Wallet Not Created.",
				"244"=>"Wallet Not Activated.",
				"301"=>"Invalid Json Request.",
				"302"=>"Invalid Request type.",
				"303"=>"Merchant Id can not be blank.",
				"304"=>"App IP is blank.",
				"305"=>"Merchant Id not registered.",
				"306"=>"Merchant Id expired.",
				"307"=>"Security key expired.",
				"308"=>"Invalid amount",
				"309"=>"Invalid order id",
				"310"=>"Invalid currency",
				"311"=>"Invalid device id",
				"317"=>"Invalid payment mode",
				"318"=>"Invalid customer id",
				"319"=>"Invalid industry type",
				"323"=>"User is blocked",
				"324"=>"Duplicate customer id",
				"325"=>"Duplicate order id",
				"326"=>"Merchant is not associated",
				"327"=>"Channel is not associated",
				"328"=>"Invalid PaytmId",
				"330"=>"Paytm checksum mismatch.",
				"332"=>"Order id cannott be greater than 50 characters.",
				"333"=>"Customer id cannot be greater than 50 characters.",
				"334"=>"Invalid Order Id.",
				"335"=>"Invalid merchant Id.",
				"336"=>"Invalid transaction type.",
				"343"=>"Invalid Token",
				"344"=>"Invalid wallet type",
				"400"=>"Transaction status not confirmed yet.",
				"401"=>"Invalid transaction.",
				"402"=>"Abondoned Transaction.",
				"501"=>"System Error.",
				"502"=>"Json Encoding error.",
				"600"=>"Invalid refund request.",
				"601"=>"Refund request was raised for this transaction. But it is pending state.",
				"603"=>"Refund/Cancel for the same transaction has already been initiated for the day.",
				"605"=>"Refund initiated for a transaction, which is not settled.",
				"607"=>"Refund can not be initiated for a cancelled transaction.",
				"609"=>"Refund initiated for a rejected transaction.",
				"610"=>"Transaction fully refunded already",
				"611"=>"Refund request is in process.",
				"612"=>"This is a valid authorized transaction, but could not be cancelled due to operational reasons.",
				"613"=>"Auto refund request is in process.",
				"614"=>"Refund request is in process.",
				"615"=>"CLW Refund to Wallet request failed.",
				"616"=>"CLW Returns error response.",
				"617"=>"Refund request is already in process for the same id.",
				"618"=>"Wallet of user not created.",
				"699"=>"Wallet Refund Failed. It will be retried for next 48 hr.",
				"700"=>"Auto Refund Failed. It will be retried for next 48 hr.",
				"701"=>"Invalid ref id.",
				);
				


?>